### ISSUE TITLE
Blocks module

### ISSUE THREAD

**Issue by maxemilian-jco** [JCO-Digital/jcore-blocks#1]
**Convert to an issue when a Block repo is made**

### Todos:

- [x] Create Block module
- [x] Import old blocks
- [x] Connect the module to Ydin, Get timber working
- [x] Add block module to Kehitys, and actually get it running with Ydin + Ilme

[Module development documentation](https://github.com/JCO-Digital/jcore-maja/blob/main/docs/process.md)

Ansvarsperson: @maxemilian-jco

**Comment by maxemilian-jco** [comment]
This is now fixed, we still need to finalize the build pipeline + branch protection.

**Comment by maxemilian-jco** [comment]
Add documentation to Maja @maxemilian-jco
